config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
  get 'morrallas/agregar_saldo'
  post 'morrallas/agregar_saldo'

  post 'morrallas/cobrar'

 

=======
  
  devise_for :models
>>>>>>> solution
  get "archivos/subir_archivos"
  post "archivos/subir_archivos"
  get "archivos/listar_archivos"
  post "archivos/borrar_archivos"
  get "archivos/guardar_coments"
  post "archivos/guardar_coments"
  post "archivos/create"

get "morrallas/new"
post "morrallas/new"
  get "morrallas/agregar_saldo"
  post "morrallas/agregar_saldo"
  post "morrallas/index"
  get "morrallas/index"
  post "morrallas" => "morrallas#agregar_saldo"

  resources :morralla

  get 'modulos/index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :archivos
    resources :users

  root 'modulos#index'

end

app/models/archivo.rb
class Archivo < ActiveRecord::Base
	belongs_to :user

	validates  :archivo,
    presence: true
end

app/models/log_morralla.rb
class LogMorralla < ActiveRecord::Base
  belongs_to :user
end

app/models/log_print.rb
class LogPrint < ActiveRecord::Base
  belongs_to :user
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/morralla.rb
class Morralla < ActiveRecord::Base
  belongs_to :user

<<<<<<< HEAD
  def calculate_all_personal_resources
  #   num = Survey.count
  #   sum = Survey.sum(:personal_resources).to_f
  #   (sum/num).round(1)
   end
=======

  validates :mount, presence: true
>>>>>>> solution
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/models/pdfatexto.rb
#!/usr/bin/env ruby
require 'pdf/reader'
# Recorremos los argumentos pasados al programa
ARGV.each do |archivo|
     PDF::Reader.open(archivo) do |lector| # abrimos el archivo como pdf
          puts "Convirtiendo: #{archivo}"
          numero_pagina = 0 # un contador de paginas
          txt = lector.pages.map do |pagina| # leemos las paginas del archivo
               numero_pagina += 1
               begin
                    print "Convirtiendo Pagina #{numero_pagina}/#{lector.page_count}\r"
                    pagina.text
               rescue
                    puts "Error: La pagina #{numero_pagina}/#{lector.page_count} no se pudo convertir"
                    ''
               end
          end
          puts "\nGuardando el archivo de texto"
          File.write archivo+'.txt', txt.join("\n") # se guarda el archivo de texto
     end
end.empty? and begin
     # si no se especifico ningun archivo, le mostramos al usuario como usar el programa
     puts 'Modo de uso: '
     puts 'ruby pdfatexto.rb archivo.pdf [otro_archivo.pdf]'
end

app/models/print.rb
class Print < ActiveRecord::Base
  belongs_to :user
  validates  :q40,
    presence: true

#  before_save :calculate_all_overall_happiness

 
  # def calculate_overallhappiness_x
  #   self.overall_happiness = ((calculate_personalresources_x + calculate_organizationalsystem_x + calculate_functioningatwork_x + calculate_experienceofwork_x)/4).round(1)
  # # end
  # def calculate_all_personal_resources
  #   num = Survey.count
  #   sum = Survey.sum(:personal_resources).to_f
  #   (sum/num).round(1)
  # end
  # def calculate_all_organizational_system
  #   num = Survey.count
  #   sum = Survey.sum(:organizational_system).to_f
  #   (sum/num).round(1)
  # end
  # def calculate_all_functioning_at_work
  #   num = Survey.count
  #   sum = Survey.sum(:functioning_at_work).to_f
  #   (sum/num).round(1)
  # end
  # def calculate_all_experience_of_work
  #   num = Survey.count
  #   sum = Survey.sum(:experience_of_work).to_f
  #   (sum/num).round(1)
  # end
  # def calculate_all_overall_happiness
  #   num = Survey.count
  #   sum = Survey.sum(:overall_happiness).to_f
  #   (sum/num).round(1)
  # end

  # def ordered_values
  #   field_names = Survey.columns.map {|c| c.name }

  #   i = 41
  #   while i < 81
  #     Survey.last.send(field_names[41])
  #     i = i + 1
  #   end
  # end
end

app/models/registration.rb
 def paypal_url(return_path)
    values = {
        business: "a20130436-facilitator@utem.edu.mx",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}#{return_path}",
        invoice: id,
        amount: course.price,
        item_name: course.name,
        item_number: course.id,
        quantity: '1'
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :order

  has_many :morralla

  has_one :log_print
  has_one :log_morralla

  has_many :archivos

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
	def index
    @prints = Print.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @print = Print.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
       @print = current_user.print.new(print_params)

    respond_to do |format|
      if @print.save

        format.html { redirect_to @print, notice: 'Print was successfully created.' }
        format.json { render :show, status: :created, location: @print }
      else
        format.html { render :new }
        format.json { render json: @print.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @print.update(survey_params)
        format.html { redirect_to @print, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @print }
      else
        format.html { render :edit }
        format.json { render json: @print.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @print.destroy
    respond_to do |format|
      format.html { redirect_to prints_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @print = Print.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      if params[:print]
        params.require(:print).permit(
          :q40
        )
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/helpers/cancels_helper.rb
module CancelsHelper
end

app/helpers/historials_helper.rb
module HistorialsHelper
end

app/helpers/modulos_helper.rb
module ModulosHelper
end

app/helpers/morralla_helper.rb
module MorrallaHelper
end

app/helpers/morrallas_helper.rb
module MorrallasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/print_admin_helper.rb
module PrintAdminHelper
end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/helpers/progress_helper.rb
module ProgressHelper
end

app/helpers/user_admin_helper.rb
module UserAdminHelper
end

app/views/prints/_edit.html.erb
<%= render '/surveys/navigation'  %>
    <div class="rightColumnAdmin">
      <div class="card blacks">
        <h1>EDIT <%= resource_name.to_s.humanize.upcase %></h1>

        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
        <%= devise_error_messages! %>

        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name, autofocus: true %>
        </div>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true %>
       </div>

       <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
        <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
       <% end %>

       <div class="field">
         <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
         <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
        <%= f.password_field :current_password, autocomplete: "off" %>
      </div>

      <div class="actions">
        <%= f.submit "Update" %>
      </div>
        <% end %>

      <h1>CANCEL MY ACCOUNT</h1>

      <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

      <%= link_to "Back", surveys_path %>
    </div>
  </div>

app/views/prints/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>
  <h2>1. Sube tu archivo...</h2>
  <div class="field">
    <%= f.label :q40, "Lo vas a dejar pagado?" %><br>
    <%= f.radio_button :q40, 1, class:"radio" %>Cobrar de mi morralla
    <%= f.radio_button :q40, 2, class:"radio" %>Pago contra entrega
    
  </div>
  <div class="actions">
    <%= f.submit "Imprimir" %>
  </div>
<% end %>

app/views/prints/_navigation.html.erb
<div class="content">

    <div class="leftColumn">

        <div class="card" id="registro">
          <div class="header">
            <h1>Morralla</h1>
            <h1>Virtual</h1>
          </div>
          <div class="card top-border">
            <div class="menu-bars">
              <%= current_user.email %>
            </div>
            <div class="menu-bars">
              <%= link_to 'Home', modulos_index_path %>
            </div>
            
            <div class="menu-bars">
              <%= link_to '+Imprimir', archivo_subir_archivos_path %>
            </div>
            
            <div class="menu-bars">
              <%= link_to 'User settings', edit_user_registration_path %>
            </div>
            <div class="menu-bars">
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </div>
          </div>
        </div>

        <div class="card top-border">
            <p id="credits">
            </p>
        </div>

    </div>

app/views/prints/edit.html.erb
<%= render 'navigation' %>
    <div class="rightColumn">
      <div class="card blacks">
      <% if current_user == @survey.user %>
        <h1>EDITING SURVEY</h1>
        <%= render 'form' %>
      <%else%> 
        <h1>You cannot edit this survey.</h1>
      <%end%>
      <br>
      <%= link_to 'Back', surveys_path %>
      </div>
    </div>
  </div>
</div>

app/views/prints/index.html.erb
<%= render 'navigation' %>
      <div class="rightColumnAdmin">
        <div class="card blacks">
          <h1>Listado de impresiones pendientes</h1>
          <table class="tg">
            <tr>
             
             
              <th class="table-size">Date</th>
              <th class="table-size">Status</th>
              <th class="table-size-min"></th>
              <th class="table-size-min"></th>
            </tr>
            
            </tr>
          </table>
        </div>
            </tr>
          </table>
        </div>
        <div class="card blacks">
          <h1>STATISTICS</h1> 
          <table class="tg">
            <tr>
              <th class="table-size-ad">Usuarios en la BD</th>
              <th class="table-size-ad">Log de impresiones</th>
            </tr>
            <tr>
              <td class="table-size-ad">
                <%= User.count %>
              </td>
              <td class="table-size-ad">
        
              </td>
            </tr>
          </table>
        </div>
        
    </div>
</div>

app/views/prints/modulos.html.erb
<%= render 'navigation' %>
      <div class="rightColumnAdmin">
        <div class="card blacks">
          <h1>Listado de impresiones pendientes</h1>
          <table class="tg">
            <tr>
              <% if current_user.role == "admin" %>
              <% @users = User.all %>
              <% @users.each do |user| %>
                Name: <%= user.name %> <br>
                e-mail: <%= user.email %>
                <%= button_to "Cancel account", user,  method: :delete, data: { confirm: "Are you sure?" } %>
                   <% @surveys.each do |survey| %>
                   <%if survey.user == nil %>
                  <% survey.destroy %>
                    <%end%>
                <%end%>
                <%end%>
                <th class="table-size">User</th>
              <% end %>
              <th class="table-size">Date</th>
              <th class="table-size">Status</th>
              <th class="table-size-min"></th>
              <th class="table-size-min"></th>
            </tr>
            <% @surveys.each do |survey| %>
            <tr>
              <% if can? :read, survey %>
              <% if current_user.role == "admin" %>
                <td class="table-size"><%= survey.user.name %><%if survey.user == nil %>
                  <% survey.destroy %>
                    <%end%></td>
              <%end%>
              <td class="table-size"><%= survey.created_at %></td>
              <td class="table-size-min"><%= link_to 'Show', survey %></td>
              <% if can? :update, survey %>
                <td class="table-size-min"><%= link_to 'Edit', edit_survey_path(survey) %></td>
              <% end %>
              <% if can? :destroy, @survey %>
                <td class="table-size-min"><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
              <% end %>
              <% end %>
              <% end %>
            </tr>
          </table>
        </div>
        <% if current_user.role == "admin" %>
        <div class="card blacks">
          
          <table class="tg">
          
            <% @surveys.each do |survey| %>
            <% if can? :read, survey %>
            
              <%break%>
            <% end %>
            <% end %>
            </tr>
          </table>
        </div>
        <div class="card blacks">
          <h1>STATISTICS</h1> 
          <table class="tg">
            <tr>
              <th class="table-size-ad">Usuarios en la BD</th>
              <th class="table-size-ad">Log de impresiones</th>
            </tr>
            <tr>
              <td class="table-size-ad">
                <%= User.count %>
              </td>
              <td class="table-size-ad">
                <%= Survey.count %>
              </td>
            </tr>
          </table>
        </div>
        <% end %>
    </div>
</div>

app/views/prints/new.html.erb
<%= render 'navigation' %>
    <div class="rightColumn">
      <div class="card blacks">

        <h1>Nueva impresión</h1>
        <%= render 'form' %>
        <br>
        <%= link_to 'Back', surveys_path %>
      </div>
    </div>
  </div>
</div>

app/views/prints/show.html.erb
<%= render 'navigation' %>
    <div class="rightColumn">
      <div class="card blacks">
        <% if current_user == @survey.user %>
          <%= link_to 'Edit', edit_survey_path(@survey) %> |
        <%end%>
        <%= link_to 'Back', surveys_path %>
        <% if current_user.role == "admin" %>
          <h2>USER: <%= @survey.user.name %></h2>
        <%end%>
        <h1>Detalles de la Impresión</h1>
        
          <table class="tg">
            <tr>
              <th class="table-size-ad">Date</th>
              <th class="table-size-ad">Status</th>
            </tr>
          </table>
        
          

      
  </div>
</div>