config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
  get 'morrallas/agregar_saldo'
  post 'morrallas/agregar_saldo'

  post 'morrallas/cobrar'

 

=======
  
  devise_for :models
>>>>>>> solution
  get "archivos/subir_archivos"
  post "archivos/subir_archivos"
  get "archivos/listar_archivos"
  post "archivos/borrar_archivos"
  get "archivos/guardar_coments"
  post "archivos/guardar_coments"
  post "archivos/create"

get "morrallas/new"
post "morrallas/new"
  get "morrallas/agregar_saldo"
  post "morrallas/agregar_saldo"
  post "morrallas/index"
  get "morrallas/index"
  post "morrallas" => "morrallas#agregar_saldo"

  resources :morralla

  get 'modulos/index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :archivos
    resources :users

  root 'modulos#index'

end

app/models/archivo.rb
class Archivo < ActiveRecord::Base
	belongs_to :user

	validates  :archivo,
    presence: true
end

app/models/log_morralla.rb
class LogMorralla < ActiveRecord::Base
  belongs_to :user
end

app/models/log_print.rb
class LogPrint < ActiveRecord::Base
  belongs_to :user
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/morralla.rb
class Morralla < ActiveRecord::Base
  belongs_to :user

<<<<<<< HEAD
  def calculate_all_personal_resources
  #   num = Survey.count
  #   sum = Survey.sum(:personal_resources).to_f
  #   (sum/num).round(1)
   end
=======

  validates :mount, presence: true
>>>>>>> solution
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/models/pdfatexto.rb
#!/usr/bin/env ruby
require 'pdf/reader'
# Recorremos los argumentos pasados al programa
ARGV.each do |archivo|
     PDF::Reader.open(archivo) do |lector| # abrimos el archivo como pdf
          puts "Convirtiendo: #{archivo}"
          numero_pagina = 0 # un contador de paginas
          txt = lector.pages.map do |pagina| # leemos las paginas del archivo
               numero_pagina += 1
               begin
                    print "Convirtiendo Pagina #{numero_pagina}/#{lector.page_count}\r"
                    pagina.text
               rescue
                    puts "Error: La pagina #{numero_pagina}/#{lector.page_count} no se pudo convertir"
                    ''
               end
          end
          puts "\nGuardando el archivo de texto"
          File.write archivo+'.txt', txt.join("\n") # se guarda el archivo de texto
     end
end.empty? and begin
     # si no se especifico ningun archivo, le mostramos al usuario como usar el programa
     puts 'Modo de uso: '
     puts 'ruby pdfatexto.rb archivo.pdf [otro_archivo.pdf]'
end

app/models/print.rb
class Print < ActiveRecord::Base
  belongs_to :user
  validates  :q40,
    presence: true

#  before_save :calculate_all_overall_happiness

 
  # def calculate_overallhappiness_x
  #   self.overall_happiness = ((calculate_personalresources_x + calculate_organizationalsystem_x + calculate_functioningatwork_x + calculate_experienceofwork_x)/4).round(1)
  # # end
  # def calculate_all_personal_resources
  #   num = Survey.count
  #   sum = Survey.sum(:personal_resources).to_f
  #   (sum/num).round(1)
  # end
  # def calculate_all_organizational_system
  #   num = Survey.count
  #   sum = Survey.sum(:organizational_system).to_f
  #   (sum/num).round(1)
  # end
  # def calculate_all_functioning_at_work
  #   num = Survey.count
  #   sum = Survey.sum(:functioning_at_work).to_f
  #   (sum/num).round(1)
  # end
  # def calculate_all_experience_of_work
  #   num = Survey.count
  #   sum = Survey.sum(:experience_of_work).to_f
  #   (sum/num).round(1)
  # end
  # def calculate_all_overall_happiness
  #   num = Survey.count
  #   sum = Survey.sum(:overall_happiness).to_f
  #   (sum/num).round(1)
  # end

  # def ordered_values
  #   field_names = Survey.columns.map {|c| c.name }

  #   i = 41
  #   while i < 81
  #     Survey.last.send(field_names[41])
  #     i = i + 1
  #   end
  # end
end

app/models/registration.rb
 def paypal_url(return_path)
    values = {
        business: "a20130436-facilitator@utem.edu.mx",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}#{return_path}",
        invoice: id,
        amount: course.price,
        item_name: course.name,
        item_number: course.id,
        quantity: '1'
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :order

  has_many :morralla

  has_one :log_print
  has_one :log_morralla

  has_many :archivos

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
end

app/controllers/modulos_controller.rb
class ModulosController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/helpers/cancels_helper.rb
module CancelsHelper
end

app/helpers/historials_helper.rb
module HistorialsHelper
end

app/helpers/modulos_helper.rb
module ModulosHelper
end

app/helpers/morralla_helper.rb
module MorrallaHelper
end

app/helpers/morrallas_helper.rb
module MorrallasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/helpers/progress_helper.rb
module ProgressHelper
end

app/helpers/user_admin_helper.rb
module UserAdminHelper
end

app/views/modulos/_navigation.html.erb
<div class="content">

    <div class="leftColumn">

        <div class="card" id="registro">
          <div class="header">
            <h1>Morralla</h1>
            <h1>Virtual</h1>
          </div>
          <div class="card top-border">
            <div class="menu-bars">
              <%= current_user.email%>

            </div>

            <div class="menu-bars">

            </div>
            <div class="menu-bars">
              <%= link_to 'Home', modulos_index_path %>
            </div>
            
            <div class="menu-bars">
              <%= link_to '+Imprimir', archivos_subir_archivos_path %>
            </div>
            
            
           
            <div class="menu-bars">
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </div>
          </div>
        </div>

        <div class="card top-border">
            <p id="credits">
            </p>
        </div>

    </div>

app/views/modulos/index.html.erb
<%= render 'navigation' %>
      <div class="rightColumnAdmin">
        <div class="card blacks">
          <h1>Modulos</h1>
          
         
        	<%= link_to image_tag('print.png', alt: 'Mostrar detalle de prospecto'), archivos_listar_archivos_path %> 
<<<<<<< HEAD
        	<%= link_to image_tag('cash1.png', alt: 'Mostrar detalle de prospecto'), morrallas_agregar_saldo_path%> 
=======
        	<%= link_to image_tag('cash1.png', alt: 'Mostrar detalle de prospecto'), morrallas_new_path%> 
>>>>>>> solution

        </div>
        
    </div>
</div>